spring:
  application:
    name: order-service

  rabbitmq:
    host: 39.224.49.226
    port: 5672
    username: admin
    password: admin 
   
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


server:  port: 8201
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka